# -- stage 1-- build stage
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# -- stage 2 -- production stage
FROM node:22-alpine
WORKDIR /app

COPY --from=builder /app /app
EXPOSE 3001
ENV PORT=3001

CMD ["npm", "start"]
